import type { CSSProperties } from "react";
import { pickImage, srcSetOf, type ResolvedMedia } from "@/lib/media";

type Props = {
  media?: ResolvedMedia | null;
  alt?: string;
  sizes?: string;
  className?: string;
  /** Use for the largest above-the-fold image only. */
  priority?: boolean;
  /** "cover" crops to the box using the focal point; "contain" preserves the full composition. */
  fit?: "cover" | "contain";
  focal?: { x: number; y: number };
  placeholderLabel?: string;
  target?: number;
};

/** Responsive image from processed derivatives, with reserved dimensions and a focal point. */
export function MediaImage({
  media, alt, sizes = "100vw", className = "", priority, fit = "cover", focal, placeholderLabel, target,
}: Props) {
  const src = media ? pickImage(media, target) : null;
  if (!media || !src) return <Placeholder className={className} label={placeholderLabel} />;
  const fx = focal?.x ?? media.focalX;
  const fy = focal?.y ?? media.focalY;
  const style: CSSProperties = {
    objectFit: fit,
    objectPosition: `${fx}% ${fy}%`,
    ...(media.blur ? { backgroundImage: `url(${media.blur})`, backgroundSize: "cover", backgroundPosition: `${fx}% ${fy}%` } : {}),
  };
  return (
    // Derivatives are generated by our worker, so next/image's optimizer isn't needed.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src.url}
      srcSet={srcSetOf(media)}
      sizes={sizes}
      width={src.w}
      height={src.h}
      alt={alt ?? media.alt}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      fetchPriority={priority ? "high" : undefined}
      className={className}
      style={style}
    />
  );
}

/** Shown wherever a photograph hasn't been supplied or published yet. */
export function Placeholder({ className = "", label }: { className?: string; label?: string }) {
  return (
    <div
      className={`relative overflow-hidden bg-gradient-to-br from-[#3a342c] via-[#1f1c18] to-ink ${className}`}
      role={label ? "img" : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
    >
      <div className="absolute inset-0 opacity-[0.08] [background-image:radial-gradient(circle_at_30%_20%,#D2B497_0,transparent_45%)]" />
      {label ? (
        <span className="absolute bottom-3 left-3 text-[11px] tracking-wide text-ivory/50">{label}</span>
      ) : null}
    </div>
  );
}
